### ISSUE TITLE
Some songs not displaying lyrics.

### ISSUE THREAD

**Issue by Miepee** [f-leoni/lyrics2#23] opened 2023-04-07 17:24 UTC
Not quite sure what might cause it, but some songs dont display lyrics. If I try to open [Paid in Full](https://genius.com/Sonata-arctica-paid-in-full-lyrics) in Lyrics 2, I just get a "You might also like" screen.

**Comment by f-leoni** [comment] 2023-04-28 10:55
Fixed in next release. It was caused by a slight change in Genius

**Closed** 2023-04-28 10:56 UTC
